# Generated by Django 2.2.2 on 2019-06-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
