# Generated by Django 2.2.2 on 2019-06-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190619_1727'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['title'], name='dashboard_s_title_44b1e4_idx'),
        ),
    ]
